name: CI/CD to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Zip for Lambda
        run: |
          mkdir -p build
          cp target/studentanalyser-0.0.1-SNAPSHOT.jar build/
          cd build && zip lambda-package.zip studentanalyser-0.0.1-SNAPSHOT.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name studentanalyzer-lambda \
            --zip-file fileb://build/lambda-package.zip
